$LOAD_PATH << '.'
require 'test/unit'
require 'tc_euclidean_distance_tests.rb'
require 'tc_simple_matching_coefficient_tests.rb'
require 'tc_jaccard_index_tests.rb'
require 'tc_pearson_correlation_tests.rb'
require 'tc_cosine_similarity_tests.rb'